### ISSUE TITLE
Cant sell items (1.21.1)

### ISSUE THREAD

**Issue by Joaofixe** [Maxlego08/zShop#11]
When I try to sell an item, it doesn’t work, but if I buy it from the shop and then sell it, it works.

Example:

If I collect 1 stack of sand and try to sell it, it doesn’t work.
but,
If I buy any item from the shop and sell it, then it works.

I'm running my server on version 1.21.1 using Purpur build 2307, with the latest versions of zshop and zmenu.

**Comment by Willi4mDev** [comment]
How did you fixed this please ?

**Comment by Joaofixe** [comment]
> How did you fixed this please ?

Go to the chanel zshop in discord you have a jar with a fix, zmenu 1.0.3.4.jar, its fixed in the chanel
